# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0002_remove_votes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jeu.Question'),
            preserve_default=False,
        ),
    ]
