# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0003_categories_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jeu.Categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votes',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jeu.Question'),
            preserve_default=False,
        ),
    ]
