# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0004_auto_20170422_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='urlpdf',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
