# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0005_auto_20170422_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
