# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0006_vote_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='scoredep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeu.User'),
        ),
    ]
