# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0007_auto_20170429_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredep',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
