# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0009_answquest'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
