# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0010_question_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voted',
        ),
    ]
