# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0011_remove_question_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answquest',
            name='answer',
            field=models.CharField(max_length=12),
        ),
    ]
