# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeu', '0012_auto_20170430_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='langue',
            field=models.CharField(default='fr', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pseudonyme',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
